knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-footer-custom: true
    footer-custom-content: ApexVenture 1.0 | Copyright  2023-[开源])