server:
  port: 8500
spring:
  cloud:
    gateway:
      routes:
        - id: apxvt-chatbot
          uri: lb://chatbot
          predicates:
            - Path=/chatbot/**

        - id: apxvt-oauth2
          uri: lb://oauth
          predicates:
            - Path=/oauth/**


#swagger
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version: openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway



